spring.application.name=rss-reader

# Server
server.port=8080
server.servlet.session.timeout=30m

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/rss_reader
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Initialize database
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:Script.sql

# Jdbc
spring.jdbc.template.fetch-size=100
spring.jdbc.template.max-rows=500

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.example.rssreader.repository=DEBUG
logging.level.org.example.rssreader.util.RSSParser=DEBUG

# Security
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=USER